name: FrostManager
main: net.frostalf.frostmanager.FrostManager
version: ${project.version}
author: Frostalf
description: Plugin to enable or disable plugins without restarting server.

commands:
    fm:
        usage: /fm (action) [Plugin Name]
        description: does performed actioned specified
        alias: [frostmanager]